# Generated by Django 4.2.4 on 2023-08-06 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elevator_number', models.IntegerField()),
                ('current_floor', models.IntegerField(default=1)),
                ('is_door_open', models.BooleanField(default=True)),
                ('direction', models.TextField(choices=[(1, 'UP'), (-1, 'DOWN'), (0, 'STANDING STILL')], default=0)),
                ('is_operational', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'elevators',
                'db_table': 'elevator',
                'ordering': ['elevator_number'],
            },
        ),
        migrations.CreateModel(
            name='ElevatorSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_name', models.CharField(max_length=100)),
                ('number_of_elevators', models.IntegerField(default=1)),
                ('number_of_floors', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'elevator_systems',
                'db_table': 'elevator_system',
                'ordering': ['number_of_elevators'],
            },
        ),
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_from_floor', models.IntegerField()),
                ('requested_to_floor', models.IntegerField()),
                ('is_serviced', models.BooleanField(default=True)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.elevator')),
            ],
            options={
                'verbose_name_plural': 'elevator_requests',
                'db_table': 'elevator_request',
                'ordering': ['elevator'],
            },
        ),
        migrations.AddField(
            model_name='elevator',
            name='elevator_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.elevatorsystem'),
        ),
    ]
